/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxarifado.view;

import almoxarifado.controle.ControleRequisitante;
import almoxarifado.controle.ControllerMaterial;
import almoxarifado.controle.ControllerPedido;
import almoxarifado.controle.ControllerRequisicao;
import almoxarifado.dao.CadastroRequisitante_Dao;
import almoxarifado.dao.Dao_CadastroMaterial;
import almoxarifado.dao.Dao_Pedido;
import almoxarifado.dao.Dao_Requisicao;
import almoxarifado.modelo.Material;
import almoxarifado.modelo.Pedido;
import almoxarifado.modelo.Requisicao;
import almoxarifado.modelo.Requisitante;
import almoxarifado.modelo.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruna
 */
public class NovaPrincipal extends javax.swing.JFrame {

    View_Categoria categoria;
    View_Departamento departamento;
    View_Fornecedores fornecedor;
    View_Material material;
    View_Requisitante requisitante;
    View_Usuario usuario;
    Usuario usuario_login;
    Requisitante Model_requi = new Requisitante();
    CadastroRequisitante_Dao Dao_requi = new CadastroRequisitante_Dao();
    ArrayList<Requisitante> listaRequi = new ArrayList<>();

    Dao_CadastroMaterial Dao_Material = new Dao_CadastroMaterial();
    Material Modet_mate = new Material();
    ArrayList<Material> listaMate = new ArrayList<>();

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelol = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();

    Requisicao requisicao;
    Dao_Requisicao dao_que;
    ArrayList<Requisicao> listaRequicao = new ArrayList<>();
    ControllerRequisicao Con_requisicao;

    Pedido pedido;
    ArrayList<Pedido> listapedido;
    ControllerPedido conPedido;
    Dao_Pedido dao_pedido;

    public NovaPrincipal() throws SQLException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        listarCliente();
        listarMaterial();
        atualizarTabela();
        limparRequisicao();
        codigoDaCombobox();
        modelol = (DefaultTableModel) TabelaPedido.getModel();
//        System.out.println(usuario_login.toString());
//        LabelNome.setText(String.valueOf(usuario_login.getNome()));
//        LabelCodigo.setText(String.valueOf(usuario_login.getCodigo()));
//        LabelFuncao.setText(usuario_login.getTipoUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTRequisicao = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txCodRequi = new javax.swing.JTextField();
        cbRequesitante = new componentes.UJComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txCodRequisiçao = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cbMaterial = new componentes.UJComboBox();
        jLabel46 = new javax.swing.JLabel();
        txCodMat = new javax.swing.JTextField();
        txQuantidade = new javax.swing.JTextField();
        btAdicionar5 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TabelaPedido = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        txSalvar = new javax.swing.JButton();
        txValorTotal = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        btAterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txPesCodigoRequi = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaRequi = new javax.swing.JTable();
        btExcluirRequisicao = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelCodigo = new javax.swing.JLabel();
        LabelFuncao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(232, 219, 180));

        jToolBar1.setBackground(new java.awt.Color(232, 219, 180));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        jLabel5.setText("             ");
        jToolBar1.add(jLabel5);

        jButton1.setBackground(new java.awt.Color(232, 219, 180));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003-ordem_1.png"))); // NOI18N
        jButton1.setText("Entrega");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jLabel4.setText("             ");
        jToolBar1.add(jLabel4);
        jToolBar1.add(jSeparator1);

        jLabel3.setText("             ");
        jToolBar1.add(jLabel3);

        jButton2.setBackground(new java.awt.Color(232, 219, 180));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002-lista-de-controle_1.png"))); // NOI18N
        jButton2.setText("Requisição");
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jLabel1.setText("             ");
        jToolBar1.add(jLabel1);
        jToolBar1.add(jSeparator2);

        jLabel2.setText("             ");
        jToolBar1.add(jLabel2);

        jButton3.setBackground(new java.awt.Color(232, 219, 180));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001-estoque_1.png"))); // NOI18N
        jButton3.setText("Estoque");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTRequisicao.setBackground(new java.awt.Color(230, 214, 165));

        jPanel8.setBackground(new java.awt.Color(230, 214, 165));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requisição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Codigo da requisitante");

        txCodRequi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txCodRequiFocusLost(evt);
            }
        });
        txCodRequi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txCodRequiMouseExited(evt);
            }
        });
        txCodRequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodRequiActionPerformed(evt);
            }
        });

        cbRequesitante.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbRequesitantePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbRequesitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequesitanteActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Nome do requesitante");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Codigo da requisiçao");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("Codigo do Material");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Nome do Material");

        cbMaterial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbMaterialPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaterialActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("Quantidade");

        txCodMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txCodMatFocusLost(evt);
            }
        });

        btAdicionar5.setText("Adicionar");
        btAdicionar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionar5ActionPerformed(evt);
            }
        });

        TabelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Material", "Quantidade", "Valor Unitario", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TabelaPedido);
        if (TabelaPedido.getColumnModel().getColumnCount() > 0) {
            TabelaPedido.getColumnModel().getColumn(0).setMinWidth(50);
            TabelaPedido.getColumnModel().getColumn(0).setPreferredWidth(50);
            TabelaPedido.getColumnModel().getColumn(0).setMaxWidth(50);
            TabelaPedido.getColumnModel().getColumn(2).setMinWidth(70);
            TabelaPedido.getColumnModel().getColumn(2).setPreferredWidth(70);
            TabelaPedido.getColumnModel().getColumn(2).setMaxWidth(70);
            TabelaPedido.getColumnModel().getColumn(3).setMinWidth(100);
            TabelaPedido.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaPedido.getColumnModel().getColumn(3).setMaxWidth(100);
            TabelaPedido.getColumnModel().getColumn(4).setMinWidth(150);
            TabelaPedido.getColumnModel().getColumn(4).setPreferredWidth(150);
            TabelaPedido.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jButton20.setText("Cancelar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txSalvar.setText("Salvar");
        txSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSalvarActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setText("Valor Total");

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAterar.setText("Alterar");
        btAterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAterarActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButton20)
                                .addGap(34, 34, 34)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 870, Short.MAX_VALUE)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txCodMat)
                            .addComponent(txCodRequi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRequesitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAdicionar5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCodRequisiçao)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(txCodRequisiçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRequesitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCodRequi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel45)
                        .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txCodMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btRemover)
                        .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46))
                    .addComponent(btAdicionar5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAterar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jTRequisicao.addTab("Cadastrar", jPanel8);

        jPanel1.setBackground(new java.awt.Color(230, 214, 165));

        jLabel6.setText("Pesquisar");

        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TabelaRequi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venta", "Requisitante", "Valor Total", "Data", "Avaliaçãol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaRequi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaRequiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaRequi);

        btExcluirRequisicao.setText("Excluir");
        btExcluirRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirRequisicaoActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed1(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(230, 214, 165));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resultado_1.png"))); // NOI18N
        jButton5.setText("Aceitar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(230, 214, 165));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/negativo.png"))); // NOI18N
        jButton7.setText("Recusar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(txPesCodigoRequi, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btExcluirRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(531, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txPesCodigoRequi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExcluirRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTRequisicao.addTab("Alterar/Consutar/Excluir", jPanel1);

        jLayeredPane1.setLayer(jTRequisicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTRequisicao)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(232, 219, 180));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Usuario"));

        jLabel7.setText("Nome:");

        jLabel8.setText("Função:");

        jLabel9.setText("Codigo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jMenuBar1.setBackground(new java.awt.Color(101, 88, 48));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medico.png"))); // NOI18N
        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/o-negocio.png"))); // NOI18N
        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prioridade.png"))); // NOI18N
        jMenuItem4.setText("Material");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simb.png"))); // NOI18N
        jMenuItem3.setText("Categoria de Material");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entregador.png"))); // NOI18N
        jMenuItem2.setText("Requisitante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa.png"))); // NOI18N
        jMenuItem5.setText("Departamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aperto-de-mao.png"))); // NOI18N
        jMenuItem6.setText("Fornecedores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002-descricao.png"))); // NOI18N
        jMenu3.setText("Relatórios");
        jMenu3.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001-distribuicao.png"))); // NOI18N
        jMenu4.setText("Distribuição");
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003-inspecao.png"))); // NOI18N
        jMenu5.setText("Pedidos");
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/definicoes (1).png"))); // NOI18N
        jMenu6.setText("Configurações");
        jMenuBar1.add(jMenu6);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1138, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void login(String nome,String codigo,String funcao){
        LabelNome.setText(nome);
        LabelCodigo.setText(codigo);
        LabelFuncao.setText(funcao);
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (usuario == null) {

            usuario = new View_Usuario();

            usuario.setLocationRelativeTo(null);
        }
        usuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (requisitante == null) {
            try {
                requisitante = new View_Requisitante();
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            requisitante.setLocationRelativeTo(null);
        }
        requisitante.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (categoria == null) {
            categoria = new View_Categoria();
            categoria.setLocationRelativeTo(null);
        }
        categoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (material == null) {
            try {
                material = new View_Material();
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            material.setLocationRelativeTo(null);
        }
        material.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (departamento == null) {
            departamento = new View_Departamento();
            departamento.setLocationRelativeTo(null);
        }
        departamento.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (fornecedor == null) {
            fornecedor = new View_Fornecedores();
            fornecedor.setLocationRelativeTo(null);
        }
        fornecedor.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            limparRequisicao();
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
// Joga os dados assim que o foco for tirado do campo txtCodMat para o comboBox
    private void txCodMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCodMatFocusLost
        if (!txCodMat.getText().isEmpty()) {
            try {
                int c = Integer.valueOf(txCodMat.getText());
                Modet_mate = new ControllerMaterial().retornaMateriaCodigo(c);
                cbMaterial.setSelectedItem(Modet_mate.getDescricao());
                codigoDaCombobox();
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txCodMatFocusLost

    private void cbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaterialActionPerformed
// Joga os dados de codigo assim que selecionado no cbMaterial 
    private void cbMaterialPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbMaterialPopupMenuWillBecomeInvisible
        if (cbMaterial.isPopupVisible()) {
            try {
                Modet_mate = new ControllerMaterial().retornaRequiNome(cbMaterial.getSelectedItem().toString());
                txCodMat.setText(String.valueOf(Modet_mate.getCodigo()));
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbMaterialPopupMenuWillBecomeInvisible
    private void codigoDaCombobox() throws SQLException {
        Modet_mate = new ControllerMaterial().retornaRequiNome(cbMaterial.getSelectedItem().toString());
        txCodMat.setText(String.valueOf(Modet_mate.getCodigo()));
        Model_requi = new ControleRequisitante().retornaRequiNome(cbRequesitante.getSelectedItem().toString());
        txCodRequi.setText(String.valueOf(Model_requi.getCodigo()));
    }
    private void cbRequesitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequesitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRequesitanteActionPerformed
// Joga os dados de codigo assim que selecionado no cbRequesitante 
    private void cbRequesitantePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbRequesitantePopupMenuWillBecomeInvisible

        if (cbRequesitante.isPopupVisible()) {
            try {
                Model_requi = new ControleRequisitante().retornaRequiNome(cbRequesitante.getSelectedItem().toString());
                txCodRequi.setText(String.valueOf(Model_requi.getCodigo()));
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbRequesitantePopupMenuWillBecomeInvisible

    private void txCodRequiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txCodRequiMouseExited

    }//GEN-LAST:event_txCodRequiMouseExited
// Joga os dados assim que o foco for tirado do campo txtCodRequi
    private void txCodRequiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCodRequiFocusLost
        if (!txCodRequi.getText().isEmpty()) {
            try {
                Model_requi = new ControleRequisitante().retornaRequiCodigo(Integer.parseInt(txCodRequi.getText()));
                cbRequesitante.setSelectedItem(Model_requi.getNome());
                codigoDaCombobox();
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txCodRequiFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btEditarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed1
        try {
            txCodRequisiçao.setText(txPesCodigoRequi.getText());
            //listapedidos();
            pedido = new Pedido();
            dao_pedido = new Dao_Pedido();

            ArrayList<Pedido> lista = dao_pedido.listaDePedidos(Integer.valueOf((txPesCodigoRequi.getText())));
            //int cont = 0 ;
            //DefaultTableModel modelotabela = (DefaultTableModel) TabelaPedido.getModel();
            modelol.setRowCount(0);

            for (int i = 0; i < lista.size(); i++) {
                modelol.addRow(new Object[]{
                    lista.get(i).getMaterial().getCodigo(),
                    lista.get(i).getMaterial().getDescricao(),
                    lista.get(i).getQuantidade(),
                    lista.get(i).getMaterial().getCustoMedio(),
                    lista.get(i).getQuantidade() * lista.get(i).getMaterial().getCustoMedio()
                });
            }

            somarValorTotaol();
            this.jTRequisicao.setSelectedIndex(0);

        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btEditarActionPerformed1
    //lista de Pedidos por Venda

    public void listapedidos() throws SQLException {
        pedido = new Pedido();
        dao_pedido = new Dao_Pedido();

        ArrayList<Pedido> lista = dao_pedido.listaDePedidos(Integer.valueOf((txPesCodigoRequi.getText())));
        //int cont = 0 ;
        //DefaultTableModel modelotabela = (DefaultTableModel) TabelaPedido.getModel();
        modelol.setRowCount(0);

        for (int i = 0; i < lista.size(); i++) {
            modelol.addRow(new Object[]{
                lista.get(i).getMaterial().getCodigo(),
                lista.get(i).getMaterial().getDescricao(),
                lista.get(i).getQuantidade(),
                lista.get(i).getMaterial().getCustoMedio(),
                lista.get(i).getQuantidade() * lista.get(i).getMaterial().getCustoMedio()
            });
        }
    }

    //---Exclui Requisições------------------------
    private void btExcluirRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirRequisicaoActionPerformed
        String s = JOptionPane.showInputDialog(this, "Digite o codigo", null, JOptionPane.QUESTION_MESSAGE);
        try {
            new Dao_Requisicao().excluir(Integer.parseInt(s));
            new Dao_Requisicao().excluirPedidos(Integer.parseInt(s));
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirRequisicaoActionPerformed

    private void btAdicionar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionar5ActionPerformed
        if (txQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                //Model_requi = Dao_requi.getRequisitanteByCodigo(Integer.parseInt(txCodRequi.getText()));
                Modet_mate = Dao_Material.getMaterialByCodigo(Integer.parseInt(txCodMat.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            //DefaultTableModel modelo1 = (DefaultTableModel) TabelaPedido.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(txQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelol.setNumRows(0);
            }
            modelol.addRow(new Object[]{
                Modet_mate.getCodigo(),
                Modet_mate.getDescricao(),
                txQuantidade.getText(),
                Modet_mate.getCustoMedio(),
                quantidade * Modet_mate.getCustoMedio()});
            somarValorTotaol();
        }
    }//GEN-LAST:event_btAdicionar5ActionPerformed

    private void txCodRequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodRequiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodRequiActionPerformed

    private void txSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSalvarActionPerformed
        int a = 0;
        try {
            requisicao = new Requisicao();
            requisicao.setRequisitante(Dao_requi.getRequisitanteByCodigo(Integer.parseInt(txCodRequi.getText())));
            requisicao.setValorTotal(Double.parseDouble(txValorTotal.getText()));
            a = new ControllerRequisicao().salvar(requisicao);
            //JOptionPane.showMessageDialog(null, a); 
            atualizarTabela();
            //limparRequisicao();

            //criando lista de pedidos
            listapedido = new ArrayList<>();
            int cont = TabelaPedido.getRowCount();
            for (int i = 0; i < cont; i++) {
                pedido = new Pedido();

                pedido.setMaterial(Dao_Material.getMateriaPorNome((String) TabelaPedido.getValueAt(i, 1)));
                //pedido.setRequisicao(requisicao);
                //pedido.setRequisicao(dao_que.buscaCodigoById(a));
                pedido.setRequisicao(a);
                pedido.setQuantidade(Integer.parseInt((String) TabelaPedido.getValueAt(i, 2)));
                //pedido.setValorUni(Double.parseDouble((String) TabelaPedido.getValueAt(i, 3)));
                listapedido.add(pedido);
            }
            //Salvar pedidos
            new Dao_Pedido().salvarListaDePedidos(listapedido);
            //conPedido.salvarPedidosEmLista(listapedido);

            limparRequisicao();
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txSalvarActionPerformed

    private void TabelaRequiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaRequiMouseClicked
        int linha = TabelaRequi.getSelectedRow();
        txPesCodigoRequi.setText(String.valueOf(TabelaRequi.getValueAt(linha, 0)));
    }//GEN-LAST:event_TabelaRequiMouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            limparRequisicao();
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int linha = TabelaPedido.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) TabelaPedido.getModel();
        modelo.removeRow(linha);
        somarValorTotaol();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAterarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAterarActionPerformed1
        try {
//            int a = Integer.parseInt((String) modelol.getValueAt(0, 2));
//            JOptionPane.showMessageDialog(this, a);
            new Dao_Requisicao().excluirPedidos(Integer.parseInt(txCodRequisiçao.getText()));

            listapedido = new ArrayList<>();
            int cont = TabelaPedido.getRowCount();
            for (int i = 0; i < cont; i++) {
                pedido = new Pedido();
                pedido.setMaterial(Dao_Material.getMateriaPorNome((String) TabelaPedido.getValueAt(i, 1)));
                String a =String.valueOf(TabelaPedido.getValueAt(i, 2));
                int quantidade = Integer.valueOf(a);
                pedido.setQuantidade(quantidade);
                
                pedido.setRequisicao(Integer.parseInt(txCodRequisiçao.getText()));
                //pedido.setValorUni(Double.parseDouble((String) TabelaPedido.getValueAt(i, 3)));
                listapedido.add(pedido);
            }
            //Salvar pedidos
            new Dao_Pedido().salvarListaDePedidos(listapedido);
            //conPedido.salvarPedidosEmLista(listapedido);

            limparRequisicao();
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAterarActionPerformed1

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

              int i = Integer.parseInt(txPesCodigoRequi.getText());
              new Dao_Requisicao().aprovacaoPositiva(i);
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarTabela();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            int i = Integer.parseInt(txPesCodigoRequi.getText());
            new Dao_Requisicao().aprovacaoNegativa(i);
        } catch (SQLException ex) {
            Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarTabela();
    }//GEN-LAST:event_jButton7ActionPerformed

    //--------------Cliente e materias para Requesição---------------------------
    private void listarCliente() throws SQLException {
        listaRequi = (ArrayList<Requisitante>) Dao_requi.TodosRequisitantesAtivos();
        // cbRequesitante.removeAllItems();
        for (int i = 0; i < listaRequi.size(); i++) {
            cbRequesitante.addItem(listaRequi.get(i).getNome());
        }
    }

    private void listarMaterial() throws SQLException {
        listaMate = (ArrayList<Material>) Dao_Material.todosMateriais();
        //cbMaterial.removeAllItems();
        for (int i = 0; i < listaMate.size(); i++) {
            cbMaterial.addItem(listaMate.get(i).getDescricao());
        }
    }

    //-----------------------------tabela de requisisoes------------------------
    //---------------------Fomataçao das tabelas--------------------------
    String tituloColuna[] = {"IdVendas", "Requisitante", "Valor", "Data", "Aprovação"};

    public void modeloDATabela(String[][] a) {

        modelo2.setDataVector(a, tituloColuna);
        TabelaRequi.setModel(new DefaultTableModel(a, tituloColuna) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        TabelaRequi.getColumnModel().getColumn(0).setPreferredWidth(30);
        TabelaRequi.getColumnModel().getColumn(1).setPreferredWidth(200);
        TabelaRequi.getColumnModel().getColumn(2).setPreferredWidth(100);
        TabelaRequi.getColumnModel().getColumn(3).setPreferredWidth(50);
        TabelaRequi.getColumnModel().getColumn(4).setPreferredWidth(70);

        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        TabelaRequi.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        TabelaRequi.setRowHeight(25);
    }

    public void atualizarTabela() {
        requisicao = new Requisicao();
        try {
            listaRequicao = (ArrayList<Requisicao>) new Dao_Requisicao().ListaDeRequisicoes();
            String dados[][] = new String[listaRequicao.size()][5];
            int i = 0;
            for (Requisicao r : listaRequicao) {
                dados[i][0] = String.valueOf(r.getId());
                dados[i][1] = r.getRequisitante().getNome();
                dados[i][2] = String.valueOf(r.getValorTotal());
                dados[i][3] = String.valueOf(r.getData());
                dados[i][4] = r.getAprovacao();
                i++;
            }
            modeloDATabela(dados);
            TabelaRequi.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void somarValorTotaol() {
        double soma = 0, valor;
        int cont = TabelaPedido.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) TabelaPedido.getValueAt(i, 4);
            soma += valor;
        }
        txValorTotal.setText(String.valueOf(soma));
    }

    private void somarValorTotaol2() {
        double soma = 0, valor;
        int cont = TabelaPedido.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = Double.parseDouble((String) TabelaPedido.getValueAt(i, 4));
            soma += valor;
        }
        txValorTotal.setText(String.valueOf(soma));
    }

    private void limparRequisicao() throws SQLException {
        txValorTotal.setText("");
        txCodRequisiçao.setText("");
        txQuantidade.setText("");
        modelo = (DefaultTableModel) TabelaPedido.getModel();
        modelo.setNumRows(0);
        codigoDaCombobox();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NovaPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NovaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelFuncao;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JTable TabelaPedido;
    private javax.swing.JTable TabelaRequi;
    private javax.swing.JButton btAdicionar5;
    private javax.swing.JButton btAterar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluirRequisicao;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btRemover;
    private componentes.UJComboBox cbMaterial;
    private componentes.UJComboBox cbRequesitante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTRequisicao;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txCodMat;
    private javax.swing.JTextField txCodRequi;
    private javax.swing.JTextField txCodRequisiçao;
    private javax.swing.JTextField txPesCodigoRequi;
    private javax.swing.JTextField txQuantidade;
    private javax.swing.JButton txSalvar;
    private javax.swing.JTextField txValorTotal;
    // End of variables declaration//GEN-END:variables
}
