/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxarifado.view;

import almoxarifado.dao.Dao_CadastroFornecedores;
import almoxarifado.modelo.Fornecedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruna
 */
public class View_Fornecedores extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Fornecedor> fornecedores;
    Dao_CadastroFornecedores daoFornecedo;
    Fornecedor f;
    public View_Fornecedores() {
        f = new Fornecedor();
        daoFornecedo = new Dao_CadastroFornecedores();
        fornecedores = new ArrayList<>();
        initComponents();
        atualizarTabela();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txRazao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txNomeFantasia = new javax.swing.JTextField();
        txCNPJ_CPF = new javax.swing.JTextField();
        txInscricao_RG = new javax.swing.JTextField();
        btnovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        ButtonSalvarAlterar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txCep = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txComplemento = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txcidade = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txTelefone2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txBanco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txConta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txAgencia = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabCadastro = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txCodigoPes = new javax.swing.JTextField();
        btPesquisaCod = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txNomePes = new javax.swing.JTextField();
        btpesquisaNome = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Codigo");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 20, 43, 17);

        txCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txCodigo);
        txCodigo.setBounds(100, 20, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Razão ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(50, 60, 50, 17);

        txRazao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txRazao);
        txRazao.setBounds(100, 60, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nome Fantasia ");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(350, 60, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CNPJ ou CPF");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 100, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Inscrição Estadual ou RG");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(290, 100, 151, 17);

        txNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txNomeFantasia);
        txNomeFantasia.setBounds(450, 60, 230, 30);

        txCNPJ_CPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txCNPJ_CPF);
        txCNPJ_CPF.setBounds(100, 100, 150, 30);

        txInscricao_RG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txInscricao_RG);
        txInscricao_RG.setBounds(450, 100, 230, 30);

        btnovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/script_add.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedores");

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door_in.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disk.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        ButtonSalvarAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonSalvarAlterar.setText("Alterar");
        ButtonSalvarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarAlterarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nome da Rua");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(10, 20, 90, 17);

        txRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(txRua);
        txRua.setBounds(100, 20, 260, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bairro");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(50, 60, 35, 17);

        txBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(txBairro);
        txBairro.setBounds(100, 60, 260, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Estado");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(370, 60, 50, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nº");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(380, 20, 30, 17);

        txCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCepActionPerformed(evt);
            }
        });
        jPanel5.add(txCep);
        txCep.setBounds(100, 100, 100, 30);

        cbEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        jPanel5.add(cbEstado);
        cbEstado.setBounds(420, 60, 60, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CEP");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(60, 100, 30, 17);

        txNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumeroActionPerformed(evt);
            }
        });
        jPanel5.add(txNumero);
        txNumero.setBounds(420, 20, 60, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Complemento");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(490, 20, 90, 17);

        txComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txComplementoActionPerformed(evt);
            }
        });
        jPanel5.add(txComplemento);
        txComplemento.setBounds(580, 20, 110, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Cidade");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(500, 60, 50, 14);

        txcidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });
        jPanel5.add(txcidade);
        txcidade.setBounds(580, 60, 110, 30);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        jPanel6.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Telefone");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 30, 60, 17);

        txTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(txTelefone);
        txTelefone.setBounds(60, 30, 120, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("2º Telefone");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(190, 30, 70, 17);

        txTelefone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txTelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefone2ActionPerformed(evt);
            }
        });
        jPanel6.add(txTelefone2);
        txTelefone2.setBounds(270, 30, 130, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("E-mail");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(410, 30, 50, 20);

        txEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });
        jPanel6.add(txEmail);
        txEmail.setBounds(450, 30, 230, 30);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Bancarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nome do Banco");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(10, 30, 110, 17);

        txBanco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel7.add(txBanco);
        txBanco.setBounds(110, 30, 220, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Nº da Agencia");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(340, 30, 90, 17);

        txConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txContaActionPerformed(evt);
            }
        });
        jPanel7.add(txConta);
        txConta.setBounds(590, 30, 90, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Nº da Conta");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(500, 30, 90, 17);

        txAgencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAgenciaActionPerformed(evt);
            }
        });
        jPanel7.add(txAgencia);
        txAgencia.setBounds(430, 30, 60, 30);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnovo)
                        .addGap(2, 2, 2)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonSalvarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSalvarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        jTabbedPane3.addTab("Cadastro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Consulta de Fornecedores");

        JTabCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigo", "razao", "nomeFantasia", "CNPJ_CPF", "incricaoEstadual_RG"
            }
        ));
        JTabCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTabCadastro);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Codigo");

        txCodigoPes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txCodigoPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoPesActionPerformed(evt);
            }
        });

        btPesquisaCod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisaCod.setText("Pesquisar");
        btPesquisaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaCodActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nome");

        txNomePes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNomePes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomePesActionPerformed(evt);
            }
        });

        btpesquisaNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpesquisaNome.setText("Pesquisar");
        btpesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisaNomeActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txCodigoPes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPesquisaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(btAlterar))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txNomePes, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisaCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txCodigoPes)
                        .addComponent(jLabel12)
                        .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNomePes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(btpesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        jTabbedPane3.addTab("Consulta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        setSize(new java.awt.Dimension(761, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void limpar(){
        txCodigo.setText("");
        txRazao.setText("");
        txCNPJ_CPF.setText("");
        txInscricao_RG.setText("");
        txNomeFantasia.setText("");
        txRua.setText("");
        txNumero.setText("");
        txComplemento.setText("");
        txBairro.setText("");
        txcidade.setText("");
        cbEstado.setSelectedIndex(0);
        txCep.setText("");
        txBanco.setText("");
        txAgencia.setText("");
        txConta.setText("");
        txTelefone.setText("");
        txTelefone2.setText("");
        txEmail.setText("");
        inicio();
    }
    public void CampoTexto(boolean codigo, boolean razao, boolean cnpj, boolean Rg, boolean nomefan, boolean rua, boolean numero, boolean bairro,
            boolean complemento, boolean cidade , boolean estado, boolean cep,  boolean banco, boolean agencia, boolean conta, boolean telefone,boolean telefone2,
            boolean email){
        this.txCodigo.setEnabled(codigo);
        this.txRazao.setEnabled(razao);
        this.txCNPJ_CPF.setEnabled(cnpj);
        this.txInscricao_RG.setEnabled(Rg);
        this.txNomeFantasia.setEnabled(nomefan);
        this.txRua.setEnabled(rua);
        this.txNumero.setEnabled(numero);
        this.txComplemento.setEnabled(complemento);
        this.txBairro.setEnabled(bairro);
        this.txcidade.setEnabled(cidade);
        this.cbEstado.setEnabled(estado);
        this.txCep.setEnabled(cep);
        this.txBanco.setEnabled(banco);
        this.txAgencia.setEnabled(agencia);
        this.txConta.setEnabled(conta);
        this.txTelefone.setEnabled(telefone);
        this.txTelefone2.setEnabled(telefone2);
        this.txEmail.setEnabled(email);
    }
     private void botao(boolean novo, boolean salvar, boolean limpar, boolean sair, 
            boolean salvarAterar, boolean pesCodigo, boolean pesNome, boolean alterar){
        btnovo.setEnabled(novo);
        btSalvar.setEnabled(salvar);
        btLimpar.setEnabled(limpar);
        btSair.setEnabled(sair);
        ButtonSalvarAlterar.setEnabled(salvarAterar);
        btPesquisaCod.setEnabled(pesCodigo);
        btpesquisaNome.setEnabled(pesNome);
        btAlterar.setEnabled(alterar); 
    }
    private void inicio(){
    CampoTexto(false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false);
    botao(true, false, false, true, false, true, true,false);
    }
    private void txCodigoPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoPesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoPesActionPerformed

    private void txNomePesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomePesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomePesActionPerformed

    private void txAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAgenciaActionPerformed

    private void txContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txContaActionPerformed

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailActionPerformed

    private void txTelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefone2ActionPerformed

    private void txComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txComplementoActionPerformed

    private void txNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumeroActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void txCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCepActionPerformed

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        boolean CV = camposVazios();
        if(CV){
        f = new Fornecedor();
        
        f.setRazao(txRazao.getText());
        f.setNomeFantasia(txNomeFantasia.getText());
        f.setCnpj_cpf(txCNPJ_CPF.getText());
        f.setInscricaoEstadual_RG(txInscricao_RG.getText());
        f.setRua(txRua.getText());
        f.setNumero(txNumero.getText());
        f.setComplemento(txComplemento.getText());
        f.setBairro(txBairro.getText());
        f.setCidade(txcidade.getText());
        f.setEstado((String) cbEstado.getSelectedItem());
        f.setCep(txCep.getText());
        f.setBanco(txBanco.getText());
        f.setAgencia(txAgencia.getText());
        f.setConta(txConta.getText());
        f.setTelefone1(txTelefone.getText());
        f.setTelefone2(txTelefone2.getText());
        f.setEmail(txEmail.getText());
        
        try {
            daoFornecedo.salvar(f);
        } catch (SQLException ex) {
            Logger.getLogger(View_Fornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "SALVO");
        atualizarTabela();
        limpar();
        }else{
                JOptionPane.showMessageDialog(null, "A campos a serem preenchidos");
     }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void JTabCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabCadastroMouseClicked
        if (JTabCadastro.getSelectedRow() != -1) {
        int a = Integer.valueOf(JTabCadastro.getValueAt(JTabCadastro.getSelectedRow(), 0).toString());
        txCodigoPes.setText(JTabCadastro.getValueAt(JTabCadastro.getSelectedRow(), 0).toString());
        try{

           f = daoFornecedo.getUsuarioByCodigo(a);
           txCodigo.setText(String.valueOf(f.getCodigo()));
           txRazao.setText(f.getRazao());
           txCNPJ_CPF.setText(f.getCnpj_cpf());
           txInscricao_RG.setText(f.getInscricaoEstadual_RG());
           txNomeFantasia.setText(f.getNomeFantasia());
           txRua.setText(f.getRua());
           txBairro.setText(f.getBairro());
           txNumero.setText((f.getNumero()));
           txComplemento.setText(f.getComplemento());
           txcidade.setText(f.getCidade());
           txCep.setText(f.getCep());
           cbEstado.setSelectedItem(f.getEstado());
           txBanco.setText(f.getBanco());
           txAgencia.setText(f.getAgencia());
           txConta.setText(f.getConta());
           txTelefone.setText(f.getTelefone1());
           txTelefone2.setText(f.getTelefone2());
           txEmail.setText(f.getEmail());


//               botao(true,false,true,true,true,true,false,true);
//               campo(true,false,false,false,false,false,false,false);     
        }catch(Exception ex){
            ex.printStackTrace();
        }
            btAlterar.setEnabled(true);
        }
    
    }//GEN-LAST:event_JTabCadastroMouseClicked

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        limpar();
        botao(false, true, true, true, false, true, true, false);
        CampoTexto(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true,true);
    }//GEN-LAST:event_btnovoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
           if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair?") == 0)
     {
         this.dispose();
     } 
    }//GEN-LAST:event_btSairActionPerformed
    private boolean camposVazios(){
         if(txRazao.getText().isEmpty()
            || txCNPJ_CPF.getText().isEmpty()
            || txNomeFantasia.getText().isEmpty()
            || txInscricao_RG.getText().isEmpty() 
            || txRua.getText().isEmpty()||txNumero.getText().isEmpty()
            ||txBairro.getText().isEmpty()||txcidade.getText().isEmpty()
            ||cbEstado.getSelectedItem().equals(" ")){
             return false;
         }else{
             return true;
         }
    }
    private void ButtonSalvarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarAlterarActionPerformed
        int o = JOptionPane.showConfirmDialog(null, "Você Quer Alterar os Dados Cadastrados");
        if (o == 0) {
            boolean v = camposVazios();
            if (v) {
                f.setRazao(txRazao.getText());
                f.setNomeFantasia(txNomeFantasia.getText());
                f.setCnpj_cpf(txCNPJ_CPF.getText());
                f.setInscricaoEstadual_RG(txInscricao_RG.getText());
                f.setRua(txRua.getText());
                f.setNumero(txNumero.getText());
                f.setComplemento(txComplemento.getText());
                f.setBairro(txBairro.getText());
                f.setCidade(txcidade.getText());
                f.setEstado((String) cbEstado.getSelectedItem());
                f.setCep(txCep.getText());
                f.setBanco(txBanco.getText());
                f.setAgencia(txAgencia.getText());
                f.setConta(txConta.getText());
                f.setTelefone1(txTelefone.getText());
                f.setTelefone2(txTelefone2.getText());
                f.setEmail(txEmail.getText());
        
                        
                try {
                    daoFornecedo.getAlterar(f);
                } catch (SQLException ex) {
                    Logger.getLogger(View_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "ALTERADO");
                atualizarTabela();
                limpar();
            }
        }
    }//GEN-LAST:event_ButtonSalvarAlterarActionPerformed

    private void btPesquisaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaCodActionPerformed
        if(txCodigoPes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Escolha um codigo");
        }
        else{
            try{
            f = daoFornecedo.getUsuarioByCodigo(Integer.parseInt(txCodigoPes.getText()));
            if(f == null){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado");
            }
            else{
                          txCodigo.setText(String.valueOf(f.getCodigo()));
           txRazao.setText(f.getRazao());
           txCNPJ_CPF.setText(f.getCnpj_cpf());
           txInscricao_RG.setText(f.getInscricaoEstadual_RG());
           txNomeFantasia.setText(f.getNomeFantasia());
           txRua.setText(f.getRua());
           txBairro.setText(f.getBairro());
           txNumero.setText((f.getNumero()));
           txComplemento.setText(f.getComplemento());
           txcidade.setText(f.getCidade());
           txCep.setText(f.getCep());
           cbEstado.setSelectedItem(f.getEstado());
           txBanco.setText(f.getBanco());
           txAgencia.setText(f.getAgencia());
           txConta.setText(f.getConta());
           txTelefone.setText(f.getTelefone1());
           txTelefone2.setText(f.getTelefone2());
           txEmail.setText(f.getEmail());
           BuscaCodigo();

//               botao(true,false,true,true,true,true,false,true);
//               campo(true,false,false,false,false,false,false,false);     
            }
            }catch(Exception ex){
                ex.printStackTrace();
            }
            btAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisaCodActionPerformed

    private void btpesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisaNomeActionPerformed
        if(txNomePes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite o que esta procurando");
        }else{
        BuscaTabela();
        }
    }//GEN-LAST:event_btpesquisaNomeActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
         if(txCodigoPes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Escolha um para Alterar");
        }
        else{
            
            this.jTabbedPane3.setSelectedIndex(0);
            CampoTexto(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true,true);
            botao(false, false, true, true, true, true, true, false);
            txCodigoPes.setText("");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       atualizarTabela();
       txCodigoPes.setText("");
       btAlterar.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed
     public void atualizarTabela(){
      f = new Fornecedor();
        try {
           fornecedores = (ArrayList<Fornecedor>) daoFornecedo.todosUsuarios();
            String dados[][] = new String[fornecedores.size()][8];
            int i = 0;
            for (Fornecedor f : fornecedores) {
                
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getRazao();
                dados[i][2] = f.getNomeFantasia();
                dados[i][3] = f.getCnpj_cpf();
                dados[i][4] = f.getInscricaoEstadual_RG();
                i++;
            }
            String tituloColuna[] = {"Codigo", "Razão", "Nome", "CNPJ/CPF","Inscrião/RG"};
            modelo.setDataVector(dados, tituloColuna);
            JTabCadastro.setModel(modelo);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
     private void BuscaCodigo(){
        f = new Fornecedor();
        try {
            f = daoFornecedo.getUsuarioByCodigo(Integer.valueOf(txCodigoPes.getText()));
            String dados[][] = new String[1][5];
            int i = 0;
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getRazao();
                dados[i][2] = f.getNomeFantasia();
                dados[i][3] = f.getCnpj_cpf();
                dados[i][4] = f.getInscricaoEstadual_RG();
                i++;
            
            String tituloColuna[] = {"Codigo", "Razão", "Nome", "CNPJ/CPF","Inscrião/RG"};
            modelo.setDataVector(dados, tituloColuna);
            JTabCadastro.setModel(modelo);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void BuscaTabela(){
        f = new Fornecedor();
        try {
            fornecedores = (ArrayList<Fornecedor>) daoFornecedo.BuscaUsuarios(txNomePes.getText());
            String dados[][] = new String[fornecedores.size()][8];
            int i = 0;
            for (Fornecedor f : fornecedores) {
                
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getRazao();
                dados[i][2] = f.getNomeFantasia();
                dados[i][3] = f.getCnpj_cpf();
                dados[i][4] = f.getInscricaoEstadual_RG();
                i++;
            }
            String tituloColuna[] = {"Codigo", "Razão", "Nome", "CNPJ/CPF","Inscrião/RG"};
            modelo.setDataVector(dados, tituloColuna);
            JTabCadastro.setModel(modelo);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvarAlterar;
    private javax.swing.JTable JTabCadastro;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisaCod;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btpesquisaNome;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField txAgencia;
    private javax.swing.JTextField txBairro;
    private javax.swing.JTextField txBanco;
    private javax.swing.JTextField txCNPJ_CPF;
    private javax.swing.JTextField txCep;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txCodigoPes;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JTextField txConta;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txInscricao_RG;
    private javax.swing.JTextField txNomeFantasia;
    private javax.swing.JTextField txNomePes;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txRazao;
    private javax.swing.JTextField txRua;
    private javax.swing.JTextField txTelefone;
    private javax.swing.JTextField txTelefone2;
    private javax.swing.JTextField txcidade;
    // End of variables declaration//GEN-END:variables
}
